"""final db update

Revision ID: 007c4a4a63d2
Revises: e559c9cc4864
Create Date: 2021-12-25 12:05:52.979651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007c4a4a63d2'
down_revision = 'e559c9cc4864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Numeric(precision=4), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['customer.cust_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['cars.model_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.add_column('cars', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('cars', sa.Column('img_url', sa.String(length=50), nullable=False))
    op.add_column('cars', sa.Column('year', sa.Numeric(precision=4), nullable=False))
    op.drop_column('cars', 'model_name')
    op.drop_column('cars', 'model_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('model_year', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False))
    op.add_column('cars', sa.Column('model_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('cars', 'year')
    op.drop_column('cars', 'img_url')
    op.drop_column('cars', 'name')
    op.drop_table('bookings')
    # ### end Alembic commands ###
