"""add categories table

Revision ID: 023668d0738a
Revises: fc9da6e8e240
Create Date: 2022-01-11 16:41:01.326322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023668d0738a'
down_revision = 'fc9da6e8e240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
