"""final db update 3

Revision ID: 034d44bff66e
Revises: 50b47a6de384
Create Date: 2021-12-25 12:15:05.293115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034d44bff66e'
down_revision = '50b47a6de384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('customer', sa.Column('address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'address')
    op.drop_column('cars', 'description')
    # ### end Alembic commands ###
