"""add comments field

Revision ID: 0902eb94dc4e
Revises: 034d44bff66e
Create Date: 2021-12-25 18:39:03.770977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0902eb94dc4e'
down_revision = '034d44bff66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testdrives', sa.Column('comments', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testdrives', 'comments')
    # ### end Alembic commands ###
