"""add booking_color

Revision ID: 0a75a6427448
Revises: c6c3aab7dd7d
Create Date: 2022-01-11 10:01:12.632951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a75a6427448'
down_revision = 'c6c3aab7dd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_color', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'booking_color')
    # ### end Alembic commands ###
