"""remove other fields

Revision ID: 37ba87713c9f
Revises: 69235270fe8b
Create Date: 2021-12-31 14:55:41.607094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ba87713c9f'
down_revision = '69235270fe8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'name')
    op.drop_column('bookings', 'price')
    op.drop_column('bookings', 'color')
    op.drop_column('bookings', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('year', sa.NUMERIC(precision=4, scale=0), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
