"""final db update 2

Revision ID: 50b47a6de384
Revises: 007c4a4a63d2
Create Date: 2021-12-25 12:14:47.959894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b47a6de384'
down_revision = '007c4a4a63d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'description')
    op.drop_column('customer', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('cars', sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
