"""casacde deletes

Revision ID: 69235270fe8b
Revises: e6f8ffc72eb0
Create Date: 2021-12-31 08:27:38.212022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69235270fe8b'
down_revision = 'e6f8ffc72eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_model_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_cust_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'customer', ['cust_id'], ['cust_id'], ondelete='cascade')
    op.create_foreign_key(None, 'bookings', 'cars', ['model_id'], ['model_id'], ondelete='cascade')
    op.drop_constraint('testdrives_cust_id_fkey', 'testdrives', type_='foreignkey')
    op.drop_constraint('testdrives_model_id_fkey', 'testdrives', type_='foreignkey')
    op.create_foreign_key(None, 'testdrives', 'cars', ['model_id'], ['model_id'], ondelete='cascade')
    op.create_foreign_key(None, 'testdrives', 'customer', ['cust_id'], ['cust_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testdrives', type_='foreignkey')
    op.drop_constraint(None, 'testdrives', type_='foreignkey')
    op.create_foreign_key('testdrives_model_id_fkey', 'testdrives', 'cars', ['model_id'], ['model_id'])
    op.create_foreign_key('testdrives_cust_id_fkey', 'testdrives', 'customer', ['cust_id'], ['cust_id'])
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_cust_id_fkey', 'bookings', 'customer', ['cust_id'], ['cust_id'])
    op.create_foreign_key('bookings_model_id_fkey', 'bookings', 'cars', ['model_id'], ['model_id'])
    # ### end Alembic commands ###
