"""cascade deletion for categories

Revision ID: 9853a2cb1b53
Revises: d7a332b15320
Create Date: 2022-01-11 21:49:57.427597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9853a2cb1b53'
down_revision = 'd7a332b15320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cars_category_id_fkey', 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'categories', ['category_id'], ['category_id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key('cars_category_id_fkey', 'cars', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###
