"""booking_price

Revision ID: c6c3aab7dd7d
Revises: 37ba87713c9f
Create Date: 2021-12-31 15:28:44.257791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c3aab7dd7d'
down_revision = '37ba87713c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'booking_price')
    # ### end Alembic commands ###
