"""add testdrives

Revision ID: ce8926d37dbe
Revises: 81fbd81c70f9
Create Date: 2021-12-12 09:40:02.426186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8926d37dbe'
down_revision = '81fbd81c70f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testdrives',
    sa.Column('testdrive_id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('testdrive_date', sa.Date(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cust_id'], ['customer.cust_id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['cars.model_id'], ),
    sa.PrimaryKeyConstraint('testdrive_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testdrives')
    # ### end Alembic commands ###
