"""add categories relation

Revision ID: d7a332b15320
Revises: 023668d0738a
Create Date: 2022-01-11 16:50:01.304571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a332b15320'
down_revision = '023668d0738a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cars', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'category_id')
    # ### end Alembic commands ###
