"""update fields

Revision ID: e559c9cc4864
Revises: ce8926d37dbe
Create Date: 2021-12-25 11:46:43.652484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e559c9cc4864'
down_revision = 'ce8926d37dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('model_name', sa.String(length=30), nullable=False))
    op.drop_column('cars', 'car_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('car_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('cars', 'model_name')
    # ### end Alembic commands ###
