"""update img_url to img_name

Revision ID: e6f8ffc72eb0
Revises: 0902eb94dc4e
Create Date: 2021-12-25 20:37:46.792648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f8ffc72eb0'
down_revision = '0902eb94dc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('img_name', sa.String(length=50), nullable=False))
    op.drop_column('cars', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('img_url', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('cars', 'img_name')
    # ### end Alembic commands ###
